### ISSUE TITLE
Add organized and good content to the About Page

### ISSUE THREAD

**Issue by jeoffreyduke** [jeoffreyduke/clann#12]
![Screenshot 2022-10-13 at 14-06-08 About _ Clann](https://user-images.githubusercontent.com/85391775/195604377-7d58b201-b12a-41bf-919e-2507a9f3bf99.png)

**Comment by ahamedafri** [comment]
shall I try this one also

**Comment by jeoffreyduke** [comment]
Yes, of course!

**Comment by Abhay5855** [comment]
Can you assign me this issue please

**Comment by jeoffreyduke** [comment]
Can you open a new issue that says "Improve the content in the About page", then i will assign that one to you, thanks

**Comment by jeoffreyduke** [comment]
> Can you assign me this issue please

Can you open a new issue that says "Improve the content in the About page", then i will assign that one to you, thanks

**Comment by Abhay5855** [comment]
@jeoffreyduke  https://github.com/jeoffreyduke/clann/issues/15 I have created as per you have suggested now can you assign it to me please
