### ISSUE TITLE
Fix the broken link in readme page 

### ISSUE THREAD

**Issue by ahamedafri** [jeoffreyduke/clann#16]
**Issue:** The contribution page link is broken in the readme file

 **Status:** shall I fix this one?

![Screenshot (44)](https://user-images.githubusercontent.com/86359752/195739678-ee9e4704-08e2-49c3-9b24-575fe96ec12d.png)

**Comment by jeoffreyduke** [comment]
> **Issue:** The contribution page link is broken in the readme file
> 
>  **Status:** shall I fix this one?
> 
> 
> ![Screenshot (44)](https://user-images.githubusercontent.com/86359752/195739678-ee9e4704-08e2-49c3-9b24-575fe96ec12d.png)
> 

Of course, buddy✊🏾
