### ISSUE TITLE
[FEATURE] Add a guest login button in the sign in page

### ISSUE THREAD

**Issue by jeoffreyduke** [jeoffreyduke/clann#22]
It doesn't need to work just make it look good, I will make it functional.

**Comment by manojku1803** [comment]
Hey assign to me @jeoffreyduke

**Comment by jeoffreyduke** [comment]
> Hey assign to me @jeoffreyduke 

Sure thing

**Comment by jeoffreyduke** [comment]
> Hey assign to me @jeoffreyduke

Any update?

**Comment by manojku1803** [comment]
Please explain me what to do in this?

**Comment by jeoffreyduke** [comment]
In the Sign in page just before the google and facebook buttons, just add a similar button that says: guest login, use the css to give it style, to look similar to the google and facebook buttons(you can give it similar className or sth). That is all you need to do, the button does not even need to be functional. Do you understand now? Do you have any questions?

**Comment by manojku1803** [comment]
Please tell in which folder the changes are to be do? I don't find the folder...

**Comment by jeoffreyduke** [comment]
https://github.com/jeoffreyduke/clann/blob/master/pages/signin.jsx
