### ISSUE TITLE
[FEATURE] Change "No rooms yet" in favorites page to a fun looking SVG that says something similar visually

### ISSUE THREAD

**Issue by jeoffreyduke** [jeoffreyduke/clann#23]
![Screenshot_20221014-185211.png](https://user-images.githubusercontent.com/85391775/195911324-57f06b1b-4d8a-4ee1-8392-63a40cb404b4.png)

Make sure it's responsive and looks goods across the media queries used in the project(Find in the Favorites.module.css). 

You can get good looking SVGs from undraw.co

Also make sure that SVG has the theme color.

**Comment by S-Parker7000** [comment]
i am on it

**Comment by jeoffreyduke** [comment]
> i am on it

You got it
