### ISSUE TITLE
[FEATURE] Change the "coming soon" in Popular and Friends pages to a component that will show an SVG and text that says "Page is under construction"

### ISSUE THREAD

**Issue by jeoffreyduke** [jeoffreyduke/clann#29]
![Screenshot 2022-10-18 at 20-30-01 Popular _ Clann](https://user-images.githubusercontent.com/85391775/196526111-cb506728-e744-433d-bd19-80e832282d4c.png)

Something similar has been done already with the favorites page; so refer to this issue (type https://github.com/jeoffreyduke/clann/pull/28) for hints on how to take this task on.

The SVG you will use is already stored in assets as "construction.svg".

Follow the steps on the reference issue and this task should be very easy.

In the end it should look something like this:
![Screenshot 2022-10-18 at 20-22-15 Favorites _ Clann](https://user-images.githubusercontent.com/85391775/196525773-5fe9cd46-2e36-4428-a7cf-b89ae85d29c3.png)

**Comment by ghubrakesh** [comment]
Hello @jeoffreyduke, I am willing to contribute in your project. Kindly assign it to me. Thank you.

**Comment by jeoffreyduke** [comment]
> Hello @jeoffreyduke, I am willing to contribute in your project. Kindly assign it to me. Thank you.

Alright, good luck 💪🏾

**Comment by jeoffreyduke** [comment]
> Hello @jeoffreyduke, I am willing to contribute in your project. Kindly assign it to me. Thank you.

Don't forget to check the referenced issue for clarification.

**Comment by ghubrakesh** [comment]
Hey @jeoffreyduke, I think I am unable to complete this task. You can assign it to someone else.
