### ISSUE TITLE
[FEATURE] Change cursor to pointer when user hover on Account and Profile to indicate that it can be clicked

### ISSUE THREAD

**Issue by Eugene44-hub** [jeoffreyduke/clann#30]
Change cursor to pointer when user hover on Account and Profile to indicate that it can be clicked
![image](https://user-images.githubusercontent.com/75457464/196827108-50e9ae15-9ec8-430c-b553-093b75cac5ad.png)

**Comment by Eugene44-hub** [comment]
Please Kindly assign to me

**Comment by agr1ms** [comment]
Is this issue open right now?

**Comment by vivsh1999** [comment]
I can fix this, assign me if possible

**Comment by jeoffreyduke** [comment]
> Is this issue open right now?

Yes, it is

**Comment by jeoffreyduke** [comment]
> Is this issue open right now?

Have you started working on this?

**Comment by Eugene44-hub** [comment]
> > Is this issue open right now?
> 
> Have you started working on this?

Yes i have
