### ISSUE TITLE
Create an about page and link it to "About" in the dropdown menu

### ISSUE THREAD

**Issue by jeoffreyduke** [jeoffreyduke/clann#7]
![Screenshot 2022-10-13 at 11-23-40 Home _ Clann](https://user-images.githubusercontent.com/85391775/195572413-23bdbbc9-403f-4208-bf92-19819e5608af.png)

**Comment by ahamedafri** [comment]
can you assign me to this issue?

**Comment by jeoffreyduke** [comment]
Yeah, sure thing
